theme: minima
title: Lunave's blog
author: JiseleTiburcio19
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
Hello! In this blog I will be posting and talking about my art journey and findings. As well as discussions
  about my favorite shows. Enjoy my little corner of the internet :D!!
# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
